version: '3.8'

services:
  freeswitch:
    image: deker1176/freeswitch:latest
    container_name: freeswitch
    network_mode: "host"
    volumes:
      - ./conf:/usr/local/freeswitch/conf
      - ./db:/usr/local/freeswitch/db
      - ./log:/usr/local/freeswitch/log
      - ./recordings:/usr/local/freeswitch/recordings
      - ./scripts:/usr/local/freeswitch/scripts
      - ./sounds:/usr/local/freeswitch/sounds
    restart: unless-stopped
 